import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./Navbar";
import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./AuthProvider/AuthProvider";
import QueryProvider from "./QueryProvider";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.variable}>
                <QueryProvider>
                    <AuthProvider>
                        <Theme
                            accentColor="violet"
                            panelBackground="solid"
                            radius="large"
                        >
                            <Navbar />
                            <main className="p-5">
                                <Container>{children}</Container>
                            </main>
                        </Theme>
                    </AuthProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
